FROM quay.io/opendatahub/odh-midstream-python-base-3-12:latest

ENV UV_INDEX_STRATEGY=unsafe-best-match

COPY distribution/constraints.txt ${APP_ROOT}/constraints.txt
COPY distribution/requirements.txt ${APP_ROOT}/requirements.txt
RUN uv pip install --constraint ${APP_ROOT}/constraints.txt -r ${APP_ROOT}/requirements.txt

COPY --chmod=755 distribution/install-common.sh ${APP_ROOT}/install-common.sh
ENV DOCLING_ARTIFACTS_PATH="${APP_ROOT}/.cache/docling/models"
RUN ${APP_ROOT}/install-common.sh
ENV TIKTOKEN_CACHE_DIR="${APP_ROOT}/.cache/tiktoken"

{config_labels}

COPY distribution/config.yaml ${APP_ROOT}/config.yaml
COPY --chmod=755 distribution/entrypoint.sh ${APP_ROOT}/entrypoint.sh

ENTRYPOINT [ "/opt/app-root/entrypoint.sh" ]
