ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ARG OGX_VERSION
ARG TARGETARCH

LABEL com.redhat.component="ogx-cpu-rhel9-container" \
      name="ogx/cpu-rhel9" \
      description="OGX ${OGX_VERSION} for CPU on RHEL 9" \
      summary="OGX for CPU" \
      maintainer="['managed-open-data-hub@redhat.com']" \
      io.k8s.display-name="OGX for CPU" \
      io.k8s.description="OGX ${OGX_VERSION} for CPU on RHEL 9" \
      io.openshift.expose-services="" \
      com.redhat.license_terms="https://www.redhat.com/en/about/eulas#RHAIIS" \
      com.redhat.aiplatform.image="${BASE_IMAGE}"

{config_labels}

COPY distribution/constraints.txt ${APP_ROOT}/constraints.txt
COPY distribution/requirements.txt ${APP_ROOT}/requirements.txt
RUN uv pip install https://packages.redhat.com/api/pulp-content/public-rhai/rhoai/3.5/cpu-ubi9-test/models_dev-1.0.398-2-py3-none-any.whl https://packages.redhat.com/api/pulp-content/public-rhai/rhoai/3.5/cpu-ubi9-test/azure_ai_contentunderstanding-1.1.0-2-py3-none-any.whl \
    && uv pip install --constraint ${APP_ROOT}/constraints.txt -r ${APP_ROOT}/requirements.txt

USER 0
# install missing RPMs (online, requires subscription)
# RUN ${APP_ROOT}/lib/tools/fromager-rpm-check.py --check-dnf -y --dnf-clean
# TODO: check if public-repos.sh is still needed
RUN ${APP_ROOT}/lib/tools/public-repos.sh
USER ${CNB_USER_ID}:${CNB_GROUP_ID}

# scan for missing RPMs (offline), missing libraries / symbols, and selftest
# AIPCC-3688: do not scan the container for missing libraries and symbols
# re-add ${APP_ROOT}/lib/tools/scanlibs.py below once milvus-lite build is fixed
# TODO: check if selftest.py is still needed
RUN ${APP_ROOT}/lib/tools/fromager-rpm-check.py --check-rpmdb \
    && ${APP_ROOT}/lib/tools/selftest.py

# OGX configuration
COPY --chmod=755 distribution/install-common.sh ${APP_ROOT}/install-common.sh
ENV DOCLING_ARTIFACTS_PATH="${APP_ROOT}/.cache/docling/models"
RUN ${APP_ROOT}/install-common.sh
ENV TIKTOKEN_CACHE_DIR="${APP_ROOT}/.cache/tiktoken"
COPY distribution/config.yaml ${APP_ROOT}/config.yaml
COPY --chmod=755 distribution/entrypoint.sh ${APP_ROOT}/entrypoint.sh

ENTRYPOINT [ "/opt/app-root/entrypoint.sh" ]
