#!/usr/bin/env python3
# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the terms described in the LICENSE file in
# the root directory of this source tree.

# Usage: ./distribution/build.py

import shutil
import subprocess
import sys
import os
import re
import shlex
from pathlib import Path

from ruamel.yaml import YAML

# Allowed characters for version strings: alphanumeric, dots, hyphens, plus, underscores
# Covers semver tags (v0.7.1+rhaiv.1), branch names (main, release-0.5.x), and short SHAs
_VERSION_PATTERN = re.compile(r"^[0-9a-zA-Z._+\-/]+$")


def _validate_version(version: str) -> str:
    """Validate a version string contains only safe characters.

    Raises ValueError if the version contains shell metacharacters or
    other unexpected characters that could lead to injection.
    """
    if not version or not _VERSION_PATTERN.match(version):
        raise ValueError(
            f"Invalid version format: {version!r}. "
            "Only alphanumeric characters, dots, hyphens, plus signs, underscores, and slashes are allowed."
        )
    return version


STRIPPED_PROVIDER_TYPES = {
    "inline::sentence-transformers",
    "inline::milvus",
    "inline::faiss",
}

STRIPPED_CONFIG_HEADER = (
    "# This file is automatically generated from build.yaml\n"
    "# by distribution/build.py - do not edit manually.\n"
    "#\n"
    "# Stripped provider types (dependency only - available via custom config.yaml):\n"
)


def _load_versions() -> dict[str, str]:
    """Load version strings from distribution/versions.env."""
    versions = {}
    versions_path = Path(__file__).parent / "versions.env"
    with open(versions_path) as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, value = line.split("=", 1)
                versions[key.strip()] = value.strip()
    return versions


def _init_versions() -> tuple[str, str]:
    """Resolve OGX_VERSION and OGX_CLIENT_VERSION from versions.env and environment."""
    versions = _load_versions()
    for val in versions.values():
        _validate_version(val)

    ogx_version: str
    if override := os.getenv("OGX_VERSION"):
        ogx_version = _validate_version(override)
    else:
        ogx_version = f"v{versions['OGX_VERSION']}+{versions['OGX_RHAI_VERSION']}"

    ogx_client_version: str
    if client := versions.get("OGX_CLIENT_VERSION"):
        ogx_client_version = client
    else:
        base_version = ogx_version.split("+")[0]
        ogx_client_version = ".".join(base_version.split(".")[:3])

    return ogx_version, ogx_client_version


OGX_VERSION, OGX_CLIENT_VERSION = _init_versions()
BASE_REQUIREMENTS = [
    f"ogx=={OGX_VERSION}",
]

# TODO(efenness): It's likely that we don't need many of these dependencies - let's see what we can delete
# Constrain packages we are patching to ensure reliable and repeatable build
PINNED_DEPENDENCIES = [
    "'kfp-kubernetes==2.14.6'",
    "'pyarrow>=21.0.0'",
    "'botocore==1.35.88'",
    "'boto3==1.35.88'",
    "'aiobotocore==2.16.1'",
    "'setuptools==80.10.2'",
    "'milvus-lite==2.5.1'",
]

source_install_command_pypi_client = """uv pip install --no-cache 'ogx-api@git+https://github.com/opendatahub-io/ogx.git@{ogx_version}#subdirectory=src/ogx_api'
uv pip install --no-cache --no-deps git+https://github.com/opendatahub-io/ogx.git@{ogx_version}
uv pip install --no-cache --no-deps ogx-client=={ogx_client_version}"""

source_install_command_git_client = """uv pip install --no-cache 'ogx-api@git+https://github.com/opendatahub-io/ogx.git@{ogx_version}#subdirectory=src/ogx_api'
uv pip install --no-cache --no-deps git+https://github.com/opendatahub-io/ogx.git@{ogx_version}"""


def get_ogx_install(ogx_version):
    if not is_install_from_source(ogx_version):
        return

    print(f"Installing ogx from source: {ogx_version}")

    if is_version_tag(ogx_version):
        template = source_install_command_pypi_client
    else:
        template = source_install_command_git_client

    result = template.replace("{ogx_version}", ogx_version)
    result = result.replace("{ogx_client_version}", OGX_CLIENT_VERSION)
    return result.rstrip()


def is_version_tag(version_str):
    """Check if this looks like a version tag (e.g., v0.5.0, 0.5.0, v0.5.0+rhai0) vs a branch name (e.g., main, release-0.5.x)."""
    # Strip +rhai suffix if present
    base = version_str.split("+")[0]

    # Version tags typically start with 'v' followed by a digit, or just start with a digit
    # Examples: v0.5.0, v1.2.3, 0.5.0
    # Branch names: main, develop, release-0.5.x, feature/foo
    if base.startswith("v") and len(base) > 1 and base[1].isdigit():
        return True
    if base[0].isdigit():
        return True
    return False


def is_install_from_source(ogx_version):
    """Check if version string requires git install (branch/commit) vs PyPI (version tag)."""
    if "+rhai" in ogx_version:
        return True
    if is_version_tag(ogx_version):
        return False
    return True


def check_command_installed(command, package_name=None):
    """Check if a command is installed and accessible."""
    if not shutil.which(command):
        if package_name:
            print(
                f"Error: {command} not found. Please run uv pip install {package_name}"
            )
        else:
            print(f"Error: {command} not found. Please install it.")
        sys.exit(1)


def check_ogx_version():
    """Check if the ogx version in BASE_REQUIREMENTS matches the installed version."""
    try:
        result = subprocess.run(
            ["ogx", "stack", "--version"],
            capture_output=True,
            text=True,
            check=True,
        )
        installed_version = result.stdout.strip()

        expected_version = None
        for req in BASE_REQUIREMENTS:
            if req.startswith("ogx=="):
                expected_version = req.split("==")[1]
                break

        if expected_version and installed_version != expected_version:
            print("Error: ogx version mismatch!")
            print(f"  Expected: {expected_version}")
            print(f"  Installed: {installed_version}")
            sys.exit(1)

    except subprocess.CalledProcessError as e:
        print(f"Warning: Could not check ogx version: {e}")
        print("Continuing without version validation...")


def install_ogx_from_source(ogx_version):
    """Install ogx from source using git."""
    print("installing ogx from source...")
    version = _validate_version(ogx_version)
    try:
        result = subprocess.run(
            [
                "uv",
                "pip",
                "install",
                f"git+https://github.com/opendatahub-io/ogx.git@{version}",
            ],
            check=True,
            capture_output=True,
            text=True,
        )
        if result.stdout:
            print(result.stdout)
    except subprocess.CalledProcessError as e:
        print(f"Error installing ogx: {e}")
        if e.stdout:
            print(f"stdout: {e.stdout}")
        if e.stderr:
            print(f"stderr: {e.stderr}")
        sys.exit(1)


def generate_stripped_config():
    """Generate a stripped config.yaml from build.yaml, removing dependency-only providers."""
    build_path = Path("distribution/build.yaml")
    output_path = Path("distribution/config.yaml")

    if not build_path.exists():
        print(f"Error: {build_path} not found")
        sys.exit(1)

    ryaml = YAML()
    ryaml.preserve_quotes = True
    ryaml.width = 4096

    with open(build_path, "r") as f:
        config = ryaml.load(f)

    # Validate that every entry in STRIPPED_PROVIDER_TYPES exists in build.yaml
    all_provider_types = {
        p.get("provider_type")
        for provider_list in config.get("providers", {}).values()
        if isinstance(provider_list, list)
        for p in provider_list
        if isinstance(p, dict)
    }
    missing = STRIPPED_PROVIDER_TYPES - all_provider_types
    if missing:
        print(
            f"Error: STRIPPED_PROVIDER_TYPES not found in build.yaml: {sorted(missing)}"
        )
        sys.exit(1)

    providers = config.get("providers", {})
    for api in list(providers.keys()):
        provider_list = providers[api]
        if isinstance(provider_list, list):
            for i in range(len(provider_list) - 1, -1, -1):
                p = provider_list[i]
                if (
                    isinstance(p, dict)
                    and p.get("provider_type") in STRIPPED_PROVIDER_TYPES
                ):
                    del provider_list[i]

    header = STRIPPED_CONFIG_HEADER + "".join(
        f"#   - {t}\n" for t in sorted(STRIPPED_PROVIDER_TYPES)
    )

    with open(output_path, "w") as f:
        f.write(header)
        ryaml.dump(config, f)

    print(f"Successfully generated {output_path}")


def get_dependencies():
    """Execute the ogx list-deps command and capture dependencies."""
    cmd = ["ogx", "stack", "list-deps", "distribution/build.yaml"]
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, check=True)
        # Categorize and sort different types of pip install commands
        standard_deps = []
        torch_deps = []
        no_deps = []
        no_cache = []

        for line in result.stdout.splitlines():
            line = line.strip()
            if not line:  # Skip empty lines
                continue

            # New format: just packages, possibly with flags
            cmd_parts = ["uv", "pip", "install"]
            packages_str = line

            # Parse packages and flags from the line
            # Use shlex.split to properly handle quoted package names
            parts_list = shlex.split(packages_str)
            packages = []
            flags = []
            extra_index_url = None

            i = 0
            while i < len(parts_list):
                if parts_list[i] == "--extra-index-url" and i + 1 < len(parts_list):
                    extra_index_url = parts_list[i + 1]
                    flags.extend([parts_list[i], parts_list[i + 1]])
                    i += 2
                elif parts_list[i] == "--index-url" and i + 1 < len(parts_list):
                    flags.extend([parts_list[i], parts_list[i + 1]])
                    i += 2
                elif parts_list[i] in ["--no-deps", "--no-cache"]:
                    flags.append(parts_list[i])
                    i += 1
                else:
                    packages.append(parts_list[i])
                    i += 1

            # Sort and deduplicate packages
            packages = sorted(set(packages))

            # Add quotes to packages with > or < to prevent bash redirection
            packages = [
                f"'{package}'" if (">" in package or "<" in package) else package
                for package in packages
            ]

            # Pin pymilvus to 2.6.9 to avoid gRPC crash
            # 2.6.10 crashes Milvus Lite gRPC init with empty dns:/// target
            packages = [
                "'pymilvus[milvus-lite]==2.6.9'"
                if "pymilvus[milvus-lite]" in package
                else "'pymilvus==2.6.9'"
                if "pymilvus" in package
                else package
                for package in packages
            ]

            # Convert namespace packages like llama_stack_provider_ragas.extra==0.5.1
            # to extras syntax llama_stack_provider_ragas[extra]==0.5.1
            # Only match .extra immediately before a version specifier (not in version numbers)
            #
            # We are not sending a patch to llama-stack upstream because not everyone python
            # sub-module is a package, we just handle this here instead for our own packages.
            # Even though pip will just show a warning if the extra does not exist
            packages = [
                re.sub(
                    r"\.([a-zA-Z_][a-zA-Z0-9_]*)(==|>=|<=|>|<|~=|!=)",
                    r"[\1]\2",
                    package,
                )
                for package in packages
            ]
            packages = sorted(set(packages))

            # Build the command based on flags
            if extra_index_url or "--index-url" in flags:
                # Torch dependencies with extra index URL
                full_cmd = " ".join(cmd_parts + flags + packages)
                torch_deps.append(full_cmd)
            elif "--no-deps" in flags:
                full_cmd = " ".join(cmd_parts + flags + packages)
                no_deps.append(full_cmd)
            elif "--no-cache" in flags:
                full_cmd = " ".join(cmd_parts + flags + packages)
                no_cache.append(full_cmd)
            else:
                # Standard dependencies with multi-line formatting
                formatted_packages = " \\\n    ".join(packages)
                full_cmd = f"{' '.join(cmd_parts)} \\\n    {formatted_packages}"
                standard_deps.append(full_cmd)

        # Combine all dependencies in specific order
        all_deps = []

        # Add pinned dependencies FIRST to ensure version compatibility
        if PINNED_DEPENDENCIES:
            pinned_packages = " \\\n    ".join(PINNED_DEPENDENCIES)
            pinned_cmd = f"uv pip install --upgrade \\\n    {pinned_packages}"
            all_deps.append(pinned_cmd)

        all_deps.extend(sorted(standard_deps))  # Regular pip installs
        all_deps.extend(sorted(torch_deps))  # PyTorch specific installs
        all_deps.extend(sorted(no_deps))  # No-deps installs
        all_deps.extend(sorted(no_cache))  # No-cache installs

        result = "\n".join(all_deps)
        return result
    except subprocess.CalledProcessError as e:
        print(f"Error executing command: {e}")
        print(f"Command output: {e.output}")
        print(f"Command stderr: {e.stderr}")
        sys.exit(1)


def generate_install_deps_script(dependencies):
    """Generate install-deps.sh script with all Python dependencies."""
    output_path = Path("distribution/install-deps.sh")

    lines = [
        "#!/bin/bash",
        "# WARNING: This file is auto-generated. Do not modify it manually.",
        "# Generated by: distribution/build.py",
        "set -euo pipefail",
        "",
        "uv pip install sqlalchemy",
        "uv pip install opentelemetry-distro",
        "uv pip install structlog zstandard",
        "",
        dependencies.rstrip(),
        "",
        "opentelemetry-bootstrap -a requirements | grep -v opentelemetry-instrumentation-botocore | uv pip install --requirement -",
        "",
        "uv pip install tiktoken==0.12.0",
    ]

    with open(output_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    os.chmod(output_path, 0o755)
    print(f"Successfully generated {output_path}")


def generate_containerfile(ogx_install):
    """Generate Containerfile from template."""
    template_path = Path("distribution/Containerfile.in")
    output_path = Path("distribution/Containerfile")

    if not template_path.exists():
        print(f"Error: Template file {template_path} not found")
        sys.exit(1)

    with open(template_path) as f:
        template_content = f.read()

    warning = "# WARNING: This file is auto-generated. Do not modify it manually.\n# Generated by: distribution/build.py\n"

    containerfile_content = warning + template_content

    ogx_runs = ""
    if ogx_install:
        ogx_runs = "\n".join(f"RUN {line}" for line in ogx_install.strip().splitlines())
    containerfile_content = containerfile_content.replace(
        "{ogx_install_source}", ogx_runs
    )

    with open(output_path, "w") as f:
        f.write(containerfile_content)

    print(f"Successfully generated {output_path}")


def main():
    check_command_installed("uv")
    install_ogx_from_source(OGX_VERSION)

    check_command_installed("ogx", "ogx-client")

    if not is_install_from_source(OGX_VERSION):
        print("Checking ogx version...")
        check_ogx_version()

    print("Generating stripped config.yaml...")
    generate_stripped_config()

    print("Getting dependencies...")
    dependencies = get_dependencies()

    print("Getting ogx install...")
    ogx_install = get_ogx_install(OGX_VERSION)

    print("Generating install-deps.sh...")
    generate_install_deps_script(dependencies)

    print("Generating Containerfile...")
    generate_containerfile(ogx_install)

    print("Done!")


if __name__ == "__main__":
    main()
