#!/usr/bin/env python3
# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the terms described in the LICENSE file in
# the root directory of this source tree.

# Usage: ./distribution/build.py

import shutil
import subprocess
import sys
import os
import re
import shlex
from pathlib import Path

from ruamel.yaml import YAML

# Allowed characters for version strings: alphanumeric, dots, hyphens, plus, underscores
# Covers semver tags (v0.7.1+rhaiv.1), branch names (main, release-0.5.x), and short SHAs
_VERSION_PATTERN = re.compile(r"^[0-9a-zA-Z._+\-/]+$")


def _validate_version(version: str) -> str:
    """Validate a version string contains only safe characters.

    Raises ValueError if the version contains shell metacharacters or
    other unexpected characters that could lead to injection.
    """
    if not version or not _VERSION_PATTERN.match(version):
        raise ValueError(
            f"Invalid version format: {version!r}. "
            "Only alphanumeric characters, dots, hyphens, plus signs, underscores, and slashes are allowed."
        )
    return version


STRIPPED_PROVIDER_TYPES = {
    "inline::sentence-transformers",
    "inline::milvus",
    "inline::faiss",
}

STRIPPED_CONFIG_HEADER = (
    "# This file is automatically generated from build.yaml\n"
    "# by distribution/build.py - do not edit manually.\n"
    "#\n"
    "# Stripped provider types (dependency only - available via custom config.yaml):\n"
)

def _load_versions():
    """Load version strings from distribution/versions.env."""
    versions = {}
    versions_path = Path(__file__).parent / "versions.env"
    with open(versions_path) as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, value = line.split("=", 1)
                versions[key.strip()] = value.strip()
    return versions

_versions = _load_versions()
_default_version = f"v{_versions['LLAMA_STACK_VERSION']}+{_versions['LLAMA_STACK_RHAI_VERSION']}"
_raw_version = os.getenv("LLAMA_STACK_VERSION", _default_version)
LLAMA_STACK_VERSION = _validate_version(_raw_version)
LLAMA_STACK_CLIENT_VERSION = _versions.get("LLAMA_STACK_CLIENT_VERSION")
BASE_REQUIREMENTS = [
    f"llama-stack=={LLAMA_STACK_VERSION}",
]

# Constrain packages we are patching to ensure reliable and repeatable build
PINNED_DEPENDENCIES = [
    "'kfp-kubernetes==2.14.6'",
    "'pyarrow>=21.0.0'",
    "'botocore==1.35.88'",
    "'boto3==1.35.88'",
    "'aiobotocore==2.16.1'",
    # "'ibm-cos-sdk-core==2.14.2'",  # not yet in private pip index
    # "'ibm-cos-sdk==2.14.2'",  # not yet in private pip index
    "'setuptools==80.10.2'",
]

source_install_command_pypi_client = """uv pip install --no-cache 'llama-stack-api@git+https://github.com/opendatahub-io/llama-stack.git@{llama_stack_version}#subdirectory=src/llama_stack_api'
uv pip install --no-cache --no-deps git+https://github.com/opendatahub-io/llama-stack.git@{llama_stack_version}
uv pip install --no-cache --no-deps llama-stack-client=={llama_stack_client_version}"""

source_install_command_git_client = """uv pip install --no-cache 'llama-stack-api@git+https://github.com/opendatahub-io/llama-stack.git@{llama_stack_version}#subdirectory=src/llama_stack_api'
uv pip install --no-cache --no-deps git+https://github.com/opendatahub-io/llama-stack.git@{llama_stack_version}"""


def get_llama_stack_install(llama_stack_version):
    # Use explicit client version if set, otherwise derive from llama_stack_version
    # by removing +rhai suffix and restricting to x.y.z format (3 parts)
    if LLAMA_STACK_CLIENT_VERSION:
        llama_stack_client_version = LLAMA_STACK_CLIENT_VERSION
    else:
        # Remove +rhai suffix and restrict to x.y.z (e.g., v0.6.0.1+rhai0 -> v0.6.0)
        base_version = llama_stack_version.split("+")[0]
        llama_stack_client_version = ".".join(base_version.split(".")[:3])
    # If the version is a commit SHA or a short commit SHA, we need to install from source
    if is_install_from_source(llama_stack_version):
        print(f"Installing llama-stack from source: {llama_stack_version}")

        # Determine if client should come from PyPI or git
        # Version tags (v0.5.0+rhai0) use PyPI for client (stable release)
        # Branch names (main, release-0.5.x) use git for client (matching branch)
        if is_version_tag(llama_stack_version):
            # Version tag - use PyPI for client (stable release)
            template = source_install_command_pypi_client
        else:
            # Branch name - use git for client (matching branch)
            template = source_install_command_git_client

        result = template.replace("{llama_stack_version}", llama_stack_version)
        result = result.replace(
            "{llama_stack_client_version}", llama_stack_client_version
        )
        return result.rstrip()


def is_version_tag(version_str):
    """Check if this looks like a version tag (e.g., v0.5.0, 0.5.0, v0.5.0+rhai0) vs a branch name (e.g., main, release-0.5.x)."""
    # Strip +rhai suffix if present
    base = version_str.split("+")[0]

    # Version tags typically start with 'v' followed by a digit, or just start with a digit
    # Examples: v0.5.0, v1.2.3, 0.5.0
    # Branch names: main, develop, release-0.5.x, feature/foo
    if base.startswith("v") and len(base) > 1 and base[1].isdigit():
        return True
    if base[0].isdigit():
        return True
    return False


def is_install_from_source(llama_stack_version):
    """Check if version string requires git install (branch/commit) vs PyPI (version tag)."""
    # Custom versions with +rhai suffix always install from source
    if "+rhai" in llama_stack_version:
        return True
    # Version tags (v0.5.0, 0.5.0) use PyPI
    if is_version_tag(llama_stack_version):
        return False
    # Everything else (branch names, commit SHAs) install from source
    return True


def check_command_installed(command, package_name=None):
    """Check if a command is installed and accessible."""
    if not shutil.which(command):
        if package_name:
            print(
                f"Error: {command} not found. Please run uv pip install {package_name}"
            )
        else:
            print(f"Error: {command} not found. Please install it.")
        sys.exit(1)


def check_llama_stack_version():
    """Check if the llama-stack version in BASE_REQUIREMENTS matches the installed version."""
    try:
        result = subprocess.run(
            ["llama", "stack", "--version"],
            capture_output=True,
            text=True,
            check=True,
        )
        installed_version = result.stdout.strip()

        # Extract version from BASE_REQUIREMENTS
        expected_version = None
        for req in BASE_REQUIREMENTS:
            if req.startswith("llama-stack=="):
                expected_version = req.split("==")[1]
                break

        if expected_version and installed_version != expected_version:
            print("Error: llama-stack version mismatch!")
            print(f"  Expected: {expected_version}")
            print(f"  Installed: {installed_version}")
            print(
                "  If you just bumped the llama-stack version in BASE_REQUIREMENTS, you must update the version from .pre-commit-config.yaml"
            )
            sys.exit(1)

    except subprocess.CalledProcessError as e:
        print(f"Warning: Could not check llama-stack version: {e}")
        print("Continuing without version validation...")


def install_llama_stack_from_source(llama_stack_version):
    """Install llama-stack from source using git."""
    print("installing llama-stack from source...")
    version = _validate_version(llama_stack_version)
    try:
        result = subprocess.run(
            [
                "uv",
                "pip",
                "install",
                f"git+https://github.com/opendatahub-io/llama-stack.git@{version}",
            ],
            check=True,
            capture_output=True,
            text=True,
        )
        # Print stdout if there's any output
        if result.stdout:
            print(result.stdout)
    except subprocess.CalledProcessError as e:
        print(f"Error installing llama-stack: {e}")
        if e.stdout:
            print(f"stdout: {e.stdout}")
        if e.stderr:
            print(f"stderr: {e.stderr}")
        sys.exit(1)


def generate_stripped_config():
    """Generate a stripped config.yaml from build.yaml, removing dependency-only providers."""
    build_path = Path("distribution/build.yaml")
    output_path = Path("distribution/config.yaml")

    if not build_path.exists():
        print(f"Error: {build_path} not found")
        sys.exit(1)

    ryaml = YAML()
    ryaml.preserve_quotes = True
    ryaml.width = 4096

    with open(build_path, "r") as f:
        config = ryaml.load(f)

    # Validate that every entry in STRIPPED_PROVIDER_TYPES exists in build.yaml
    all_provider_types = {
        p.get("provider_type")
        for provider_list in config.get("providers", {}).values()
        if isinstance(provider_list, list)
        for p in provider_list
        if isinstance(p, dict)
    }
    missing = STRIPPED_PROVIDER_TYPES - all_provider_types
    if missing:
        print(
            f"Error: STRIPPED_PROVIDER_TYPES not found in build.yaml: {sorted(missing)}"
        )
        sys.exit(1)

    providers = config.get("providers", {})
    for api in list(providers.keys()):
        provider_list = providers[api]
        if isinstance(provider_list, list):
            for i in range(len(provider_list) - 1, -1, -1):
                p = provider_list[i]
                if (
                    isinstance(p, dict)
                    and p.get("provider_type") in STRIPPED_PROVIDER_TYPES
                ):
                    del provider_list[i]

    header = STRIPPED_CONFIG_HEADER + "".join(
        f"#   - {t}\n" for t in sorted(STRIPPED_PROVIDER_TYPES)
    )

    with open(output_path, "w") as f:
        f.write(header)
        ryaml.dump(config, f)

    print(f"Successfully generated {output_path}")


def get_dependencies():
    """Execute the llama stack build command and capture dependencies."""
    cmd = ["llama", "stack", "list-deps", "distribution/build.yaml"]
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, check=True)
        # Categorize and sort different types of pip install commands
        standard_deps = []
        torch_deps = []
        no_deps = []
        no_cache = []

        for line in result.stdout.splitlines():
            line = line.strip()
            if not line:  # Skip empty lines
                continue

            # New format: just packages, possibly with flags
            cmd_parts = ["uv", "pip", "install"]
            packages_str = line

            # Parse packages and flags from the line
            # Use shlex.split to properly handle quoted package names
            parts_list = shlex.split(packages_str)
            packages = []
            flags = []
            extra_index_url = None

            i = 0
            while i < len(parts_list):
                if parts_list[i] == "--extra-index-url" and i + 1 < len(parts_list):
                    extra_index_url = parts_list[i + 1]
                    flags.extend([parts_list[i], parts_list[i + 1]])
                    i += 2
                elif parts_list[i] == "--index-url" and i + 1 < len(parts_list):
                    flags.extend([parts_list[i], parts_list[i + 1]])
                    i += 2
                elif parts_list[i] in ["--no-deps", "--no-cache"]:
                    flags.append(parts_list[i])
                    i += 1
                else:
                    packages.append(parts_list[i])
                    i += 1

            # Sort and deduplicate packages
            packages = sorted(set(packages))

            # Add quotes to packages with > or < to prevent bash redirection
            packages = [
                f"'{package}'" if (">" in package or "<" in package) else package
                for package in packages
            ]

            # Pin pymilvus to 2.6.9 to avoid gRPC crash
            # 2.6.10 crashes Milvus Lite gRPC init with empty dns:/// target
            packages = [
                "'pymilvus[milvus-lite]==2.6.9'"
                if "pymilvus[milvus-lite]" in package
                else "'pymilvus==2.6.9'"
                if "pymilvus" in package
                else package
                for package in packages
            ]

            # Convert namespace packages like llama_stack_provider_ragas.extra==0.5.1
            # to extras syntax llama_stack_provider_ragas[extra]==0.5.1
            # Only match .extra immediately before a version specifier (not in version numbers)
            #
            # We are not sending a patch to llama-stack upstream because not everyone python
            # sub-module is a package, we just handle this here instead for our own packages.
            # Even though pip will just show a warning if the extra does not exist
            packages = [
                re.sub(
                    r"\.([a-zA-Z_][a-zA-Z0-9_]*)(==|>=|<=|>|<|~=|!=)",
                    r"[\1]\2",
                    package,
                )
                for package in packages
            ]
            packages = sorted(set(packages))

            # Build the command based on flags
            if extra_index_url or "--index-url" in flags:
                # Torch dependencies with extra index URL
                full_cmd = " ".join(cmd_parts + flags + packages)
                torch_deps.append(full_cmd)
            elif "--no-deps" in flags:
                full_cmd = " ".join(cmd_parts + flags + packages)
                no_deps.append(full_cmd)
            elif "--no-cache" in flags:
                full_cmd = " ".join(cmd_parts + flags + packages)
                no_cache.append(full_cmd)
            else:
                # Standard dependencies with multi-line formatting
                formatted_packages = " \\\n    ".join(packages)
                full_cmd = f"{' '.join(cmd_parts)} \\\n    {formatted_packages}"
                standard_deps.append(full_cmd)

        # Combine all dependencies in specific order
        all_deps = []

        # Add pinned dependencies FIRST to ensure version compatibility
        if PINNED_DEPENDENCIES:
            pinned_packages = " \\\n    ".join(PINNED_DEPENDENCIES)
            pinned_cmd = f"uv pip install --upgrade \\\n    {pinned_packages}"
            all_deps.append(pinned_cmd)

        all_deps.extend(sorted(standard_deps))  # Regular pip installs
        all_deps.extend(sorted(torch_deps))  # PyTorch specific installs
        all_deps.extend(sorted(no_deps))  # No-deps installs
        all_deps.extend(sorted(no_cache))  # No-cache installs

        result = "\n".join(all_deps)
        return result
    except subprocess.CalledProcessError as e:
        print(f"Error executing command: {e}")
        print(f"Command output: {e.output}")
        print(f"Command stderr: {e.stderr}")
        sys.exit(1)


def generate_install_deps_script(dependencies):
    """Generate install-deps.sh script with all Python dependencies."""
    output_path = Path("distribution/install-deps.sh")

    lines = [
        "#!/bin/bash",
        "# WARNING: This file is auto-generated. Do not modify it manually.",
        "# Generated by: distribution/build.py",
        "set -euo pipefail",
        "",
        "pip install sqlalchemy",
        "uv pip install opentelemetry-distro",
        "uv pip install structlog",
        "",
        dependencies.rstrip(),
        "",
        "opentelemetry-bootstrap -a requirements | grep -v opentelemetry-instrumentation-botocore | uv pip install --requirement -",
        "",
        "uv pip install tiktoken==0.12.0",
        "",
    ]

    with open(output_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    os.chmod(output_path, 0o755)
    print(f"Successfully generated {output_path}")


def generate_containerfile(llama_stack_install):
    """Generate Containerfile from template."""
    template_path = Path("distribution/Containerfile.in")
    output_path = Path("distribution/Containerfile")

    if not template_path.exists():
        print(f"Error: Template file {template_path} not found")
        sys.exit(1)

    with open(template_path) as f:
        template_content = f.read()

    warning = "# WARNING: This file is auto-generated. Do not modify it manually.\n# Generated by: distribution/build.py\n"

    containerfile_content = warning + template_content

    # Substitute llama-stack source install (version-dependent, not in install-deps.sh)
    llama_stack_runs = ""
    if llama_stack_install:
        llama_stack_runs = "\n".join(
            f"RUN {line}" for line in llama_stack_install.strip().splitlines()
        )
    containerfile_content = containerfile_content.replace(
        "{llama_stack_install_source}", llama_stack_runs
    )

    # Remove blank lines from empty substitutions
    containerfile_content = (
        "\n".join(line for line in containerfile_content.splitlines() if line.strip())
        + "\n"
    )

    with open(output_path, "w") as f:
        f.write(containerfile_content)

    print(f"Successfully generated {output_path}")


def main():
    check_command_installed("uv")
    install_llama_stack_from_source(LLAMA_STACK_VERSION)

    check_command_installed("llama", "llama-stack-client")

    # Do not perform version check if installing from source
    if not is_install_from_source(LLAMA_STACK_VERSION):
        print("Checking llama-stack version...")
        check_llama_stack_version()

    print("Generating stripped config.yaml...")
    generate_stripped_config()

    print("Getting dependencies...")
    dependencies = get_dependencies()

    print("Getting llama-stack install...")
    llama_stack_install = get_llama_stack_install(LLAMA_STACK_VERSION)

    print("Generating install-deps.sh...")
    generate_install_deps_script(dependencies)

    print("Generating Containerfile...")
    generate_containerfile(llama_stack_install)

    print("Done!")


if __name__ == "__main__":
    main()
