#!/usr/bin/env python3
# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the terms described in the LICENSE file in
# the root directory of this source tree.

# Usage: ./distribution/build.py

import shutil
import subprocess
import sys
import os
import re
import shlex
import tempfile
from collections.abc import Generator
from contextlib import contextmanager
from pathlib import Path
from typing import NamedTuple

from ruamel.yaml import YAML

# Allowed characters for version strings: alphanumeric, dots, hyphens, plus, underscores
# Covers semver tags (v0.7.1+rhaiv.1), branch names (main, release-0.5.x), and short SHAs
_VERSION_PATTERN = re.compile(r"^[0-9a-zA-Z._+\-/]+$")

OGX_GIT_REPO = "https://github.com/opendatahub-io/ogx.git"

PINNED_DEPENDENCIES = [
    'milvus-lite==2.5.1; platform_machine != "ppc64le"',
]

CONSTRAINTS_FILE = Path("distribution/constraints.txt")

STRIPPED_PROVIDER_TYPES = {
    "inline::sentence-transformers",
    "inline::milvus",
    "inline::faiss",
}

STRIPPED_CONFIG_HEADER = (
    "# This file is automatically generated from build.yaml\n"
    "# by distribution/build.py - do not edit manually.\n"
    "#\n"
    "# Stripped provider types (dependency only - available via custom config.yaml):\n"
)


def _validate_version(version: str) -> str:
    """Validate a version string contains only safe characters.

    Raises ValueError if the version contains shell metacharacters or
    other unexpected characters that could lead to injection.
    """
    if not version or not _VERSION_PATTERN.match(version):
        raise ValueError(
            f"Invalid version format: {version!r}. "
            "Only alphanumeric characters, dots, hyphens, plus signs, underscores, and slashes are allowed."
        )
    return version


def _load_env(path: Path) -> dict[str, str]:
    """Load key=value pairs from an env file."""
    env = {}
    with open(path) as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, value = line.split("=", 1)
                env[key.strip()] = value.strip()
    return env


class OgxRequirements(NamedTuple):
    ogx_api: str
    ogx: str


def _get_ogx_requirements() -> OgxRequirements:
    """Resolve ogx package specifiers from build.env and environment."""
    env = _load_env(Path(__file__).parent / "build.env")

    version = os.getenv("OGX_VERSION") or env["OGX_VERSION"]
    _validate_version(version)

    if env.get("OGX_INSTALL_FROM_SOURCE", "").lower() == "true":
        return OgxRequirements(
            ogx_api=f"ogx-api @ git+{OGX_GIT_REPO}@{version}#subdirectory=src/ogx_api",
            ogx=f"ogx @ git+{OGX_GIT_REPO}@{version}",
        )
    else:
        return OgxRequirements(
            ogx_api=f"ogx-api=={version.split('+')[0]}",
            ogx=f"ogx=={version}",
        )


def assert_command_installed(command):
    """Check if a command is installed and accessible."""
    if not shutil.which(command):
        print(f"Error: {command} not found. Please install it.")
        sys.exit(1)


@contextmanager
def _build_venv(
    packages: list[str], constraints: Path | None = None
) -> Generator[Path]:
    """Create a temporary venv with the given packages installed. Yields the venv path."""
    with tempfile.TemporaryDirectory() as tmpdir:
        venv_path = Path(tmpdir) / "venv"

        subprocess.run(
            ["uv", "venv", "--python", sys.executable, str(venv_path)],
            check=True,
            capture_output=True,
            text=True,
        )

        cmd = [
            "uv",
            "pip",
            "install",
            "--python",
            str(venv_path / "bin" / "python"),
            *packages,
        ]
        if constraints:
            cmd.extend(["--constraint", str(constraints)])

        try:
            subprocess.run(cmd, check=True, capture_output=True, text=True)
        except subprocess.CalledProcessError as e:
            print(f"Error installing packages into temporary venv: {e}")
            if e.stdout:
                print(f"stdout: {e.stdout}")
            if e.stderr:
                print(f"stderr: {e.stderr}")
            raise

        yield venv_path


def generate_stripped_config():
    """Generate a stripped config.yaml from build.yaml, removing dependency-only providers."""
    build_path = Path("distribution/build.yaml")
    output_path = Path("distribution/config.yaml")

    if not build_path.exists():
        print(f"Error: {build_path} not found")
        sys.exit(1)

    ryaml = YAML()
    ryaml.preserve_quotes = True
    ryaml.width = 4096

    with open(build_path, "r") as f:
        config = ryaml.load(f)

    # Validate that every entry in STRIPPED_PROVIDER_TYPES exists in build.yaml
    all_provider_types = {
        p.get("provider_type")
        for provider_list in config.get("providers", {}).values()
        if isinstance(provider_list, list)
        for p in provider_list
        if isinstance(p, dict)
    }
    missing = STRIPPED_PROVIDER_TYPES - all_provider_types
    if missing:
        print(
            f"Error: STRIPPED_PROVIDER_TYPES not found in build.yaml: {sorted(missing)}"
        )
        sys.exit(1)

    providers = config.get("providers", {})
    for api in list(providers.keys()):
        provider_list = providers[api]
        if isinstance(provider_list, list):
            for i in range(len(provider_list) - 1, -1, -1):
                p = provider_list[i]
                if (
                    isinstance(p, dict)
                    and p.get("provider_type") in STRIPPED_PROVIDER_TYPES
                ):
                    del provider_list[i]

    header = STRIPPED_CONFIG_HEADER + "".join(
        f"#   - {t}\n" for t in sorted(STRIPPED_PROVIDER_TYPES)
    )

    with open(output_path, "w") as f:
        f.write(header)
        ryaml.dump(config, f)

    print(f"Successfully generated {output_path}")


def get_dependencies(ogx_bin: Path) -> list[str]:
    """Execute the ogx list-deps command and return a list of package specifiers."""
    cmd = [str(ogx_bin), "stack", "list-deps", "distribution/build.yaml"]
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, check=True)
        packages = []

        for line in result.stdout.splitlines():
            line = line.strip()
            if not line:
                continue

            parts_list = shlex.split(line)

            i = 0
            while i < len(parts_list):
                if parts_list[i] in (
                    "--extra-index-url",
                    "--index-url",
                ) and i + 1 < len(parts_list):
                    i += 2
                elif parts_list[i].startswith("--"):
                    i += 1
                else:
                    packages.append(parts_list[i])
                    i += 1

        # Convert namespace packages like llama_stack_provider_ragas.extra==0.5.1
        # to extras syntax llama_stack_provider_ragas[extra]==0.5.1
        packages = [
            re.sub(
                r"\.([a-zA-Z_][a-zA-Z0-9_]*)(==|>=|<=|>|<|~=|!=)",
                r"[\1]\2",
                pkg,
            )
            for pkg in packages
        ]

        return packages
    except subprocess.CalledProcessError as e:
        print(f"Error executing command: {e}")
        print(f"Command output: {e.output}")
        print(f"Command stderr: {e.stderr}")
        sys.exit(1)


def get_opentelemetry_packages(bootstrap_bin: Path) -> list[str]:
    """Run opentelemetry-bootstrap to discover instrumentation packages."""
    result = subprocess.run(
        [str(bootstrap_bin), "-a", "requirements"],
        capture_output=True,
        text=True,
        check=True,
    )
    packages = []
    for line in result.stdout.splitlines():
        line = line.strip()
        if line and "opentelemetry-instrumentation-botocore" not in line:
            packages.append(line)
    return packages


def generate_requirements_file(dependencies, ogx_reqs: OgxRequirements, otel_packages):
    """Generate requirements.txt with all Python dependencies."""
    output_path = Path("distribution/requirements.txt")

    all_packages = sorted(set(PINNED_DEPENDENCIES + dependencies + otel_packages))

    lines = [
        "# WARNING: This file is auto-generated. Do not modify it manually.",
        "# Generated by: distribution/build.py",
        *ogx_reqs,
        *all_packages,
    ]

    with open(output_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Successfully generated {output_path}")


def main():
    ogx_reqs = _get_ogx_requirements()

    assert_command_installed("uv")

    print("Generating stripped config.yaml...")
    generate_stripped_config()

    print("Getting dependencies...")
    with _build_venv([*ogx_reqs]) as venv:
        dependencies = get_dependencies(venv / "bin" / "ogx")

    print("Discovering opentelemetry instrumentation packages...")
    with _build_venv(
        [*ogx_reqs] + dependencies + PINNED_DEPENDENCIES,
        constraints=CONSTRAINTS_FILE,
    ) as venv:
        otel_packages = get_opentelemetry_packages(
            venv / "bin" / "opentelemetry-bootstrap"
        )

    print("Generating requirements.txt...")
    generate_requirements_file(dependencies, ogx_reqs, otel_packages)

    print("Done!")


if __name__ == "__main__":
    main()
