FROM registry.access.redhat.com/ubi9/python-312@sha256:95ec8d3ee9f875da011639213fd254256c29bc58861ac0b11f290a291fa04435
WORKDIR /opt/app-root

RUN pip install uv

COPY --chmod=755 distribution/install-deps.sh /opt/app-root/install-deps.sh
RUN /opt/app-root/install-deps.sh

{llama_stack_install_source}

COPY --chmod=755 distribution/install-common.sh /opt/app-root/install-common.sh
RUN /opt/app-root/install-common.sh
ENV TIKTOKEN_CACHE_DIR="${HOME}/.cache/tiktoken"

COPY distribution/config.yaml ${APP_ROOT}/config.yaml
COPY --chmod=755 distribution/entrypoint.sh ${APP_ROOT}/entrypoint.sh

#TODO: remove this once we have a stable version of llama-stack
# LLS server version is not aligned with the client version, so we disable the version check
# Currently, LLS client version is 0.3.0, while the server version is 0.3.0rc3+rhai0
ENV LLAMA_STACK_DISABLE_VERSION_CHECK=true

ENTRYPOINT [ "/opt/app-root/entrypoint.sh" ]
