#!/bin/bash
# WARNING: This file is auto-generated. Do not modify it manually.
# Generated by: distribution/build.py
set -euo pipefail

uv pip install sqlalchemy
uv pip install opentelemetry-distro
uv pip install structlog zstandard

uv pip install --upgrade \
    'kfp-kubernetes==2.14.6' \
    'pyarrow>=21.0.0' \
    'botocore==1.35.88' \
    'boto3==1.35.88' \
    'aiobotocore==2.16.1' \
    'setuptools==80.10.2' \
    'milvus-lite==2.5.1; platform_machine != "ppc64le"'
uv pip install \
    'fonttools>=4.60.2' \
    'google-genai>=1.69.0' \
    'mcp>=1.23.0' \
    'nltk>=3.9.4' \
    'pymilvus==2.6.9' \
    'pypdf>=6.10.0' \
    aiosqlite \
    asyncpg \
    boto3 \
    chardet \
    einops \
    faiss-cpu \
    fastapi \
    fire \
    httpx \
    matplotlib \
    numpy \
    opentelemetry-exporter-otlp-proto-http \
    opentelemetry-sdk \
    pandas \
    pillow \
    psycopg2-binary \
    pymongo \
    qdrant-client \
    redis \
    requests \
    safetensors \
    scikit-learn \
    scipy \
    sentencepiece \
    sqlalchemy[asyncio] \
    tokenizers \
    tqdm \
    transformers \
    uvicorn
uv pip install --extra-index-url https://download.pytorch.org/whl/cpu 'torchao>=0.12.0' torch torchvision
uv pip install --no-deps sentence-transformers

opentelemetry-bootstrap -a requirements | grep -v opentelemetry-instrumentation-botocore | uv pip install --requirement -

uv pip install tiktoken==0.12.0
