#!/usr/bin/env python3
"""Sync OCI config labels from the generated Containerfile into Dockerfile.konflux.

This is a downstream-only script for the RHDS fork. It reads the LABEL block
generated by build/build.py in the Containerfile and substitutes it into
Dockerfile.konflux.in to produce Dockerfile.konflux.

Usage: ./scripts/sync_labels.py
"""

import re
import sys
from pathlib import Path

CONTAINERFILE = Path("Containerfile")
TEMPLATE_PATH = Path("Dockerfile.konflux.in")
OUTPUT_PATH = Path("Dockerfile.konflux")

# Matches a multi-line LABEL instruction starting with com.ogx.config
_LABEL_PATTERN = re.compile(
    r"^(LABEL com\.ogx\.config\..*?)(?=\n(?!  ))", re.MULTILINE | re.DOTALL
)


def extract_config_labels(containerfile: Path) -> str:
    """Extract the OCI config LABEL block from a generated Containerfile."""
    if not containerfile.exists():
        print(f"Error: {containerfile} not found. Run 'build/build.py' first.")
        sys.exit(1)

    content = containerfile.read_text()
    match = _LABEL_PATTERN.search(content)
    if not match:
        print(f"Error: No 'LABEL com.ogx.config.*' block found in {containerfile}")
        sys.exit(1)

    return match.group(1)


def main():
    if not TEMPLATE_PATH.exists():
        print(f"Error: {TEMPLATE_PATH} not found")
        sys.exit(1)

    labels = extract_config_labels(CONTAINERFILE)

    template_content = TEMPLATE_PATH.read_text()
    if "{config_labels}" not in template_content:
        print(f"Error: {{config_labels}} placeholder not found in {TEMPLATE_PATH}")
        sys.exit(1)

    warning = (
        f"# WARNING: This file is auto-generated from {TEMPLATE_PATH.name}\n"
        "# by scripts/sync_labels.py - do not edit manually.\n"
    )

    # Replace version with build ARG reference for Konflux
    labels = labels.replace(
        re.search(r'com\.ogx\.distribution\.version="([^"]*)"', labels).group(1),
        "${OGX_VERSION}",
    )
    labels = labels.replace(
        re.search(r'org\.opencontainers\.image\.version="([^"]*)"', labels).group(1),
        "${OGX_VERSION}",
    )

    content = warning + template_content.replace("{config_labels}", labels)

    OUTPUT_PATH.write_text(content)
    print(f"Successfully generated {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
